android {
    namespace 'com.example.facebookaidetector'  // তোমার আসল package name
    compileSdk 34

    defaultConfig {
        applicationId "com.example.facebookaidetector"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
